# codemagic.yaml
workflows:
  build-and-test:
    name: Build and Test
    instance_type: windows_x2
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
        - manual_cert_credentials
        - firebase_credentials
        - other
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/Cocoapods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Report build start
        scripts: |
          echo "Build started"

      - name: Get flutter Packages
        script: flutter packages pub get

      - name: Build APK
        script: flutter build apk --release

      - name: Test
        script: flutter test

      - name: Build finished successfully
        script: touch ~/SUCCESS
    artifacts:
      - build/app/outputs/apk/release/*.apk
    code_signing:
      certificates:
        - distribution
      signing_profiles:
        android: my_android_profile  
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if [[ -z ${apkPath} ]]; then
              echo "No .apk files were found"
            else
              echo "Publishing .apk artifacts"
            fi

        - name: Report build status
          script: |
            if [ -a ~/SUCCESS ]; then
              echo "Build successful"
            else
              echo "Build failed"
            fi    
