workflows:
  build-and-test:
    name: Build and Test
    instance_type: windows_x2
    environment:
      android_signing:
          - testreference
      groups:        
        - firebase_credentials       
      vars:
        GOOGLE_PLAY_TRACK: beta
      flutter: stable       
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Report build start
        script: echo "Build started"
      - name: Get flutter packages
        script: flutter packages pub get
      - name: Build Flutter APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk    
    publishing:
      firebase:       
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:          
          app_id: 1:309742552743:android:0c5a96065ccef3094dbd82
          groups: 
            - androidTesters          
      email:
        recipients:
          - rafey93@gmail.com
      
