workflows:
  build-and-test:
    name: Build and Test
    instance_type: windows_x2
    environment:
      android_signing:
          - testreference
      groups:
        - keystore_credentials
        - app_store_credentials
        - manual_cert_credentials
        - firebase_credentials
        - other
      vars:
        GOOGLE_PLAY_TRACK: beta
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/Cocoapods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Report build start
        script: echo "Build started"
      - name: Get flutter packages
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --release      
      - name: Build finished successfully
        script: touch ~/SUCCESS
    artifacts:
      - build/app/outputs/apk/release/*.apk    
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if ($apkPath -eq $null) {
              echo "No .apk were found"
            } else {
              echo "Publishing .apk artifacts"
            }
        - name: Report build status
          script: |
            if (-a ~/SUCCESS) {
              echo "SUCCESS file found"
            } else {
              echo "SUCCESS file not found"
            }

