workflows:
  build-and-test:
    name: Build and Test
    instance_type: windows_x2
    environment:
      android_signing:
          - testreference
      groups:        
        - firebase_credentials       
      vars:
        GOOGLE_PLAY_TRACK: beta
      flutter: stable       
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Report build start
        script: echo "Build started"
      - name: Get flutter packages
        script: flutter packages pub get
      - name: Build Flutter APK
        script: flutter build apk --release      
      - name: Build finished successfully
        script: ~/SUCCESS
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk    
    publishing:
      firebase:       
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:          
          app_id: 1:309742552743:android:0c5a96065ccef3094dbd82
          groups: 
            - androidTesters          
      email:
        recipients:
          - rafey93@gmail.com
      scripts:
        - name: Check for apk
          script: |
            apkPath=$(find build -name "*.apk" | head -1)
            if ($apkPath -eq $null) {
              echo "No .apk were found"
            } else {
              echo "Publishing .apk artifacts"
            }
        - name: Report build status
          script: |
            if (-a ~/SUCCESS) {
              echo "SUCCESS file found"
            } else {
              echo "SUCCESS file not found"
            }

