workflows:
  build-and-test:
    name: Build and Test
    instance_type: windows_x2
    environment:
      android_signing:
          - testreference
      groups:                
        - firebase_credentials       
      vars:
        GOOGLE_PLAY_TRACK: beta
      flutter: stable
      xcode: latest
      cocoapods: default       
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Set up key properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
          ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release --build-name=1.0.5 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log     
    publishing:
      firebase:       
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:          
          app_id: 1:309742552743:android:0c5a96065ccef3094dbd82
          groups: 
            - androidTesters          
      email:
        recipients:
          - rafey93@gmail.com
      
